# Learn more at https://jupyterbook.org/customize/config.html


#######################################################################################
# Book settings
title                       : Seismology Notebook  # The title of the book. Will be placed in the left navbar.
author                      : Fu Yin  # The author of the book
logo                        : logo.png
copyright                   : "2021–2022"   # Copyright year to be placed in the footer
exclude_patterns            : [_build, Thumbs.db, .DS_Store]  # Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")
only_build_toc_files        : false   # Auto-exclude files not in the toc


#######################################################################################
# Execution settings
execute:
  execute_notebooks         : auto  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  timeout                   : 30    # The maximum time (in seconds) each notebook cell is allowed to run.
  allow_errors              : false # If `False`, when a code cell raises an error the execution is stopped, otherwise all cells are always run.


#######################################################################################
# LaTeX-specific settings
latex:
  latex_engine              : xelatex  # one of 'pdflatex', 'xelatex' (recommended for unicode), 'luatex', 'platex', 'uplatex'
  use_jupyterbook_latex     : true # use sphinx-jupyterbook-latex for pdf builds as default
  latex_documents: 
    targetname              : book.tex # Define the name of the latex output file for PDF builds


#######################################################################################
# Launch button settings
launch_buttons:
  notebook_interface        : classic  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : https://mybinder.org  # The URL of the BinderHub (e.g., https://mybinder.org)

repository:
  url                       : https://github.com/Seismology101/Notebook  # Online location of your book
  path_to_book              : book  # Optional path to your book, relative to the repository root
  branch                    : main  # Which branch of the repository should be used when creating links (optional)


#######################################################################################
# HTML-specific settings
html:
  favicon: logo.png
  use_issues_button: true
  use_repository_button: true
  use_multitoc_numbering: true    # restart chapter numbering between parts
  # announcement: "My announcement!"


#######################################################################################
# Advanced sphinx settings
sphinx:
  config:
    bibtex_reference_style: author_year

#######################################################################################
# Bib settings
bibtex_bibfiles:
  - references.bib

